import AppKit
import CoreGraphics
import Foundation

/// One recorded clipboard entry.
struct ClipboardItem: Codable, Sendable, Equatable {
    let id: UUID
    let text: String
    /// Whatever owned the menu bar when the copy landed, or nil when it could
    /// not be resolved. Attribution is a heuristic: the pasteboard itself never
    /// says who wrote to it.
    let sourceBundleID: String?
    let copiedAt: Date
    /// Whether a ⌘C/⌘X keystroke preceded the copy. Password-manager browser
    /// extensions write programmatically, so entries without a keystroke are
    /// never persisted and expire from memory quickly. See `ClipboardCapture`.
    let fromKeystroke: Bool

    init(id: UUID = UUID(), text: String, sourceBundleID: String?,
         copiedAt: Date = Date(), fromKeystroke: Bool) {
        self.id = id
        self.text = text
        self.sourceBundleID = sourceBundleID
        self.copiedAt = copiedAt
        self.fromKeystroke = fromKeystroke
    }

    /// Only keystroke-driven entries are eligible for disk.
    var isPersistable: Bool { fromKeystroke }
}

/// What may be recorded, and what may be kept. Pure decisions, kept apart from
/// the pasteboard so they can be tested directly.
///
/// No single rule here is sufficient, and each covers a case the others miss.
/// Measured on macOS 26.6.2: Bitwarden's desktop app marks its copies with
/// `org.nspasteboard.ConcealedType`, but its Chrome extension does not — an
/// extension copy arrives attributed to `com.google.Chrome` and is otherwise
/// indistinguishable from an ordinary page copy. The marker check catches the
/// former, the keystroke check catches the latter, and memory-only storage
/// (the default) is the backstop for whatever both miss.
enum ClipboardCapture {
    /// The nspasteboard.org convention. Advisory only: macOS does not enforce
    /// it, and an app that ignores it still hands us the plaintext.
    static let concealedTypes = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Apps whose copies are never recorded regardless of markers. This only
    /// helps for native password managers; one running as a browser extension
    /// is attributed to the browser and cannot be listed here.
    static let deniedSources: Set<String> = [
        "com.bitwarden.desktop",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.apple.keychainaccess",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "in.sinew.Enpass-Desktop",
    ]

    /// Frontmost lookups report this when no ordinary app owns the menu bar;
    /// it is not a meaningful source to label an entry with.
    static let unknownSource = "com.apple.loginwindow"

    enum Rejection: Equatable, Sendable {
        case empty
        case tooLarge
        case marked(String)
        case deniedSource(String)
    }

    enum Decision: Equatable, Sendable {
        case reject(Rejection)
        case record
    }

    static func decide(types: [String], sourceBundleID: String?, text: String,
                       maxBytes: Int = 128 * 1024) -> Decision {
        if text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return .reject(.empty) }
        if text.utf8.count > maxBytes { return .reject(.tooLarge) }
        if let marker = concealedTypes.first(where: types.contains) { return .reject(.marked(marker)) }
        if let source = sourceBundleID, deniedSources.contains(source) {
            return .reject(.deniedSource(source))
        }
        return .record
    }

    /// Normalizes an attribution lookup into something worth storing.
    static func source(_ bundleID: String?) -> String? {
        guard let bundleID, bundleID != unknownSource else { return nil }
        return bundleID
    }

    /// Newest first, one entry per distinct text: re-copying something already
    /// in the history promotes it rather than adding a duplicate.
    static func ingest(_ item: ClipboardItem, into items: [ClipboardItem], limit: Int) -> [ClipboardItem] {
        guard limit > 0 else { return [] }
        var kept = items.filter { $0.text != item.text }
        kept.insert(item, at: 0)
        return Array(kept.prefix(limit))
    }

    /// Drops programmatic copies once they age out. A password copied from a
    /// browser extension lives here; so does a snippet from a docs site's copy
    /// button, which is the cost of not being able to tell them apart.
    static func pruned(_ items: [ClipboardItem], now: Date = Date(),
                       volatileTTL: TimeInterval) -> [ClipboardItem] {
        items.filter { $0.fromKeystroke || now.timeIntervalSince($0.copiedAt) < volatileTTL }
    }
}

/// Records when a copy keystroke last passed through the event tap. Written
/// from the tap callback and read on the main run loop, like the other shared
/// keyboard state in Constants.swift.
nonisolated(unsafe) private var lastCopyKeystrokeAt: CFAbsoluteTime = 0

enum ClipboardKeystroke {
    /// Virtual key codes for C and X.
    private static let copyKeyCodes: Set<UInt16> = [0x08, 0x07]

    static func note(keyCode: UInt16, flags: CGEventFlags) {
        // Hyper adds Command to every key it decorates, so a Hyper chord must
        // never be mistaken for ⌘C.
        guard !hyperActive, flags.contains(.maskCommand), copyKeyCodes.contains(keyCode) else { return }
        lastCopyKeystrokeAt = CFAbsoluteTimeGetCurrent()
    }

    static func wasRecentCopy(within window: TimeInterval = 2) -> Bool {
        lastCopyKeystrokeAt > 0 && CFAbsoluteTimeGetCurrent() - lastCopyKeystrokeAt < window
    }

    /// Test seam.
    static func reset() { lastCopyKeystrokeAt = 0 }
}

/// On-disk history, written only when the user opts in.
enum ClipboardStore {
    static var directoryURL: URL {
        if let override = ProcessInfo.processInfo.environment["OMACCY_CLIPBOARD_DIR"], !override.isEmpty {
            return URL(fileURLWithPath: override)
        }
        return FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".omaccy/clipboard")
    }

    static var fileURL: URL { directoryURL.appendingPathComponent("history.json") }

    static func load() -> [ClipboardItem] {
        guard let data = try? Data(contentsOf: fileURL) else { return [] }
        return (try? JSONDecoder().decode([ClipboardItem].self, from: data)) ?? []
    }

    static func save(_ items: [ClipboardItem]) {
        let persistable = items.filter(\.isPersistable)
        do {
            try FileManager.default.createDirectory(at: directoryURL, withIntermediateDirectories: true,
                                                    attributes: [.posixPermissions: 0o700])
            let data = try JSONEncoder().encode(persistable)
            try data.write(to: fileURL, options: [.atomic])
            // .atomic replaces the file, so the mode is reapplied every write.
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: fileURL.path)
        } catch {
            fputs("omaccy-hyperkey: could not save clipboard history: \(error)\n", stderr)
        }
    }

    static func clear() {
        try? FileManager.default.removeItem(at: fileURL)
    }
}

/// Polls the pasteboard and keeps the recorded history.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    /// Identified by name rather than held as an object: `NSPasteboard` is not
    /// Sendable, so the background read reconstructs it from this instead of
    /// capturing one. Tests point it at a private pasteboard of their own.
    private let pasteboardName: NSPasteboard.Name
    private var pasteboard: NSPasteboard { NSPasteboard(name: pasteboardName) }

    private(set) var items: [ClipboardItem] = []
    private var timer: Timer?
    private var lastChangeCount: Int

    init(pasteboardName: NSPasteboard.Name = .general) {
        self.pasteboardName = pasteboardName
        self.lastChangeCount = NSPasteboard(name: pasteboardName).changeCount
    }
    private var reading = false
    private var saveWork: DispatchWorkItem?
    private var enabled = false
    private var persists = false
    private var limit = 200

    /// How long a programmatic copy survives in memory.
    private let volatileTTL: TimeInterval = 90

    var count: Int { items.count }

    func start(configuration: Configuration) {
        apply(configuration)
    }

    /// Applies the current settings, starting or stopping capture to match.
    func apply(_ configuration: Configuration) {
        limit = max(configuration.clipboardLimit, 0)
        let wasPersisting = persists
        enabled = configuration.clipboardHistory
        persists = configuration.clipboardPersist

        guard enabled else {
            // A privacy switch that leaves the history behind is not one.
            stop()
            items = []
            ClipboardStore.clear()
            return
        }

        if persists && !wasPersisting {
            items = ClipboardCapture.pruned(ClipboardStore.load() + items, volatileTTL: volatileTTL)
            saveNow()
        } else if !persists && wasPersisting {
            ClipboardStore.clear()
        }
        if timer == nil {
            // No load here: persistence turning on (including on first start,
            // when it was never off) is what reads the file, just above.
            let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated { self?.poll() }
            }
            RunLoop.main.add(timer, forMode: .common)
            self.timer = timer
            lastChangeCount = pasteboard.changeCount
        }
        items = Array(items.prefix(limit))
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func clear() {
        items = []
        ClipboardStore.clear()
    }

    /// Puts an entry back on the pasteboard and moves it to the top. The change
    /// count is claimed here so the next poll does not read our own write back
    /// in as a fresh copy -- which would re-attribute the entry to Omaccy and,
    /// having involved no ⌘C, quietly demote a persisted entry to a volatile one.
    func put(_ item: ClipboardItem) {
        let pasteboard = self.pasteboard
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        items = ClipboardCapture.ingest(item, into: items, limit: limit)
        scheduleSave()
    }

    func remove(_ id: UUID) {
        items.removeAll { $0.id == id }
        scheduleSave()
    }

    private func poll() {
        items = ClipboardCapture.pruned(items, volatileTTL: volatileTTL)
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount, !reading else { return }
        lastChangeCount = changeCount
        reading = true

        let source = ClipboardCapture.source(
            NSWorkspace.shared.menuBarOwningApplication?.bundleIdentifier
                ?? NSWorkspace.shared.frontmostApplication?.bundleIdentifier)
        let fromKeystroke = ClipboardKeystroke.wasRecentCopy()

        // Chrome and other apps provide pasteboard data lazily, so reading it
        // is an IPC round-trip to the owning app: measured at 7-13ms against
        // Chrome versus 0.8ms for plain text, and unbounded if that app is
        // wedged. The CGEventTap shares this run loop, so the read stays off it.
        let name = pasteboardName
        DispatchQueue.global(qos: .utility).async {
            let pasteboard = NSPasteboard(name: name)
            let types = (pasteboard.types ?? []).map(\.rawValue)
            let text = pasteboard.string(forType: .string)
            DispatchQueue.main.async {
                self.reading = false
                self.record(text: text, types: types, source: source, fromKeystroke: fromKeystroke)
            }
        }
    }

    private func record(text: String?, types: [String], source: String?, fromKeystroke: Bool) {
        guard enabled, let text, case .record = ClipboardCapture.decide(
            types: types, sourceBundleID: source, text: text) else { return }
        items = ClipboardCapture.ingest(
            ClipboardItem(text: text, sourceBundleID: source, fromKeystroke: fromKeystroke),
            into: items, limit: limit)
        scheduleSave()
    }

    /// Disk writes trail the copies that caused them, so a burst of copying
    /// does not turn into a burst of file writes.
    private func scheduleSave() {
        guard persists else { return }
        saveWork?.cancel()
        let work = DispatchWorkItem { [weak self] in MainActor.assumeIsolated { self?.saveNow() } }
        saveWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 2, execute: work)
    }

    private func saveNow() {
        guard persists else { return }
        ClipboardStore.save(items)
    }
}

/// Sends ⌘V to whatever is frontmost.
enum ClipboardPaste {
    /// Virtual key code for V.
    private static let vKeyCode: CGKeyCode = 0x09

    static func send() {
        let source = CGEventSource(stateID: .hidSystemState)
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false) else { return }
        for event in [down, up] {
            event.flags = .maskCommand
            // Tagged like the HID seizure path's events so our own tap passes
            // it straight through instead of decorating it with Hyper.
            event.setIntegerValueField(Constants.injectedEventField, value: Constants.injectedEventMarker)
            event.post(tap: .cghidEventTap)
        }
    }
}
